# -*- coding: utf-8 -*-
"""solve_linear_program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fas3ikLxOfkN2srsVhmYE45xvKvKPVNG
"""

import numpy as np
from scipy import optimize

def solve_linear_program(of_cfs, constr=None, constr_req=None, bounds=None):
    xmax = optimize.linprog(c=of_cfs, A_eq=constr, b_eq=constr_req, bounds=bounds).x
    xmin = optimize.linprog(c=-1. * of_cfs, A_eq=constr, b_eq=constr_req, bounds=bounds).x
    return (xmin, xmax)